MyTVStreamingService/Controllers/RecommendationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyTVStreamingService.Data;
using MyTVStreamingService.Models;

namespace MyTVStreamingService.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RecommendationsController : Controller
    {
        private readonly MyTVContext _context;

        public RecommendationsController(MyTVContext context)
        {
            _context = context;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create(int[] rec)
        {
            int[] showIds = rec;
            SortedList<int, Service> workingSet = new SortedList<int, Service>();
            foreach(int showId in showIds)
            {
                var servicesList = 
                (from showService in _context.Set<ShowService>()
                join show in _context.Set<Show>() on showService.ShowFK equals show.Id
                join service in _context.Set<Service>() on showService.ServiceFK equals service.ID
                where show.Id == showId
                orderby service.cost
                select service).ToList();
                
                Console.WriteLine(servicesList.GetType());
                // No service carries the show.
                if(servicesList.Count == 0)
                {
                    Console.WriteLine("Impossible Combination");
                    return View("Recommendation");
                }
                // Check for service already in working set which carries show
                bool showAlreadyCarried = false;
                foreach(Service service in servicesList)
                {
                    if(workingSet.ContainsKey(service.ID))
                    {
                        showAlreadyCarried = true;
                        break;
                    }
                }
                if (!showAlreadyCarried)
                {
                    // No service already in list carries show.  Add cheapest service to list.
                    workingSet.Add(servicesList.First().ID, servicesList.First());
                }
            }

            ViewData["Services"] = workingSet.Values.ToList();

            string Placeholder_Service;

            // loop through services
            // loop through shows 
            // store matching shows + service into sorted list
            // store sorted list in view data for html
            foreach (var serv in ViewData["Services"] as List<Service>)
            {
                SortedList<int, Show> showSet = new SortedList<int, Show>();
                Placeholder_Service = serv.name;

                foreach (int showId in showIds)
                {
                    var showList =
                    (from showService in _context.Set<ShowService>()
                     join show in _context.Set<Show>() on showService.ShowFK equals show.Id
                     join service in _context.Set<Service>() on showService.ServiceFK equals service.ID
                     where show.Id == showId
                     where Placeholder_Service == service.name
                     select show).ToList();

                    if (showList.Count != 0)
                    {
                        showSet.Add(showId, showList.First());
                        showIds = showIds.Where(val => val != showId).ToArray();
                    }
                }
                ViewData[Placeholder_Service] = showSet.Values.ToList();
            }

            return View("Recommendation");
        }
    }
}

MyTVStreamingService/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyTVStreamingService.Data;
using MyTVStreamingService.Models;

namespace MyTVStreamingService.Controllers
{
    public class ShowsController : Controller
    {
        private readonly MyTVContext _context;

        public ShowsController(MyTVContext context)
        {
            _context = context;
        }

        // GET: Shows
        public async Task<IActionResult> Index(string showGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from s in _context.Show
                                            orderby s.Genre
                                            select s.Genre;

            var shows = (IQueryable<Show>) from s in _context.Show
                        orderby s.Title
                        select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                shows = shows.Where(s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(showGenre))
            {
                shows = shows.Where(x => x.Genre == showGenre);
            }

            var showGenreVM = new ShowGenreViewModel
            {
                Genres = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Shows = await shows.ToListAsync()
            };

            return View(showGenreVM);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Show
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,NumberOfSeasons,Rating")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Show.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,NumberOfSeasons,Rating")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Show
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Show.FindAsync(id);
            _context.Show.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Show.Any(e => e.Id == id);
        }
    }
}

MyTVStreamingService/Views/Shared/Recommendation.cshtml
<!-- Style table and cost -->
<!-- Container for service and show -->
<style>
    table {
        margin: auto;
    }

   .box_service{
       width:1000px;
       height:200px;
       position:relative;
   }

   .cost{
       position: absolute;
       color: white;
       font-size: 50px;
       right: 100px;
       bottom: 20px;
   }

   .box_show{
       width: 100px;
       height: 200px;
       padding: 15px;
       align-content: center;
   }

</style>

<!-- Reading data from service and shows -->
<!-- Display images of service and shows by title  -->
<!-- Service/Show images located in wwwroot/css/... -->
<table>
    @foreach (var service in ViewData["Services"] as List<Service>)
    {
        <tr>
            <td colspan="10">

                <div class="box_service">
                    <img src="@Url.Content("~/css/Images_Services/" + @service.name + ".jpg")" style="width: 100%; height:100%" />
                    <div class="cost">
                        $@service.cost
                    </div>
                </div>

            </td>
        </tr>

        @foreach (var show in ViewData[@service.name] as List<Show>)
        {
            <td width="100px" height="200" align="center">
                <div class="box_show">
                    <img src="@Url.Content("~/css/Show_Images/" + @show.Title + ".jpg")" width="50" height="50" />
                    <br />
                    @show.Title
                </div>
            </td>
        }
    }
</table>

MyTVStreamingService/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<MyTVUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyTV Streaming Service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MyTV Streaming Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shows" asp-action="Index">All Shows</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminHelpdesk" asp-action="Index">Helpdesk</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListUsers">Users</a>
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListRoles">Roles</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MyTV Streaming Service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>